version: '3'
services:
  db:
    image: "mysql:5.7"
    ports:
    - "6306:3306"
    platform: linux/amd64
    environment:
    - MYSQL_DATABASE=demo_db
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
