apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal # the namespace you prefer
resources:
- ../../base

namePrefix: internal-

patchesStrategicMerge:
- server-deployment.yml