apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
spec:
  template:
    spec:
      containers:
      - name: demo-server
        env:
          - name: ENV
            value: internal