apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-server
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
      - name: demo-server
        image: gcr.io/k8s-cd-demo/fastapi-service-cd-demo
        imagePullPolicy: Always
        ports:
          - containerPort: 8000