apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-server
spec:
  type: ClusterIP
  selector:
    app: demo-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
